//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyMoveFile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
------------------------------------------------------------------------------------
		CopyMoveFile CmdLine Utility v[VERSION]
------------------------------------------------------------------------------------

Allows copying or moving files from the command line.

USAGE:  CopyMoveFile <action> /inPath <path> [/outPath <path>]

  action	Either 'copy' or 'move'.
  inPath	Path of the source file to copy/move.
  outPath	Path of the destination directory or file name (optionally
			renaming the file). If not specified, a file selection dialog will be
			displayed.

All paths are assumed to be in the current directory if a full path isn't specified.
------------------------------------------------------------------------------------
")]
        public string helpTxt {
            get {
                return ((string)(this["helpTxt"]));
            }
        }
    }
}
